name: Sync content changes

on:
  push:
    branches:
      - main

jobs:
  sync-content-changes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Open pull request
      run: gh pr create -B main -H dev --title 'Sync main branch into dev branch' --body ''
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
